/** Each country's address segment. They are written out rather than derived from the country's name, so a runtime
 * whose country names differ can't move a page. Change one only together with a redirect from the old address. */
export const countrySlugs: Record<string, string> = {
  AD: 'andorra',
  AE: 'united-arab-emirates',
  AF: 'afghanistan',
  AG: 'antigua-and-barbuda',
  AL: 'albania',
  AM: 'armenia',
  AO: 'angola',
  AR: 'argentina',
  AT: 'austria',
  AU: 'australia',
  AZ: 'azerbaijan',
  BA: 'bosnia-and-herzegovina',
  BB: 'barbados',
  BD: 'bangladesh',
  BE: 'belgium',
  BF: 'burkina-faso',
  BG: 'bulgaria',
  BH: 'bahrain',
  BI: 'burundi',
  BJ: 'benin',
  BN: 'brunei',
  BO: 'bolivia',
  BR: 'brazil',
  BS: 'bahamas',
  BT: 'bhutan',
  BW: 'botswana',
  BY: 'belarus',
  BZ: 'belize',
  CA: 'canada',
  CD: 'dr-congo',
  CF: 'central-african-republic',
  CG: 'republic-of-the-congo',
  CH: 'switzerland',
  CI: 'cote-divoire',
  CL: 'chile',
  CM: 'cameroon',
  CN: 'china',
  CO: 'colombia',
  CR: 'costa-rica',
  CU: 'cuba',
  CV: 'cape-verde',
  CY: 'cyprus',
  CZ: 'czechia',
  DE: 'germany',
  DJ: 'djibouti',
  DK: 'denmark',
  DM: 'dominica',
  DO: 'dominican-republic',
  DZ: 'algeria',
  EC: 'ecuador',
  EE: 'estonia',
  EG: 'egypt',
  ER: 'eritrea',
  ES: 'spain',
  ET: 'ethiopia',
  FI: 'finland',
  FJ: 'fiji',
  FM: 'micronesia',
  FR: 'france',
  GA: 'gabon',
  GB: 'united-kingdom',
  GD: 'grenada',
  GE: 'georgia',
  GH: 'ghana',
  GM: 'gambia',
  GN: 'guinea',
  GQ: 'equatorial-guinea',
  GR: 'greece',
  GT: 'guatemala',
  GW: 'guinea-bissau',
  GY: 'guyana',
  HK: 'hong-kong',
  HN: 'honduras',
  HR: 'croatia',
  HT: 'haiti',
  HU: 'hungary',
  ID: 'indonesia',
  IE: 'ireland',
  IL: 'israel',
  IN: 'india',
  IQ: 'iraq',
  IR: 'iran',
  IS: 'iceland',
  IT: 'italy',
  JM: 'jamaica',
  JO: 'jordan',
  JP: 'japan',
  KE: 'kenya',
  KG: 'kyrgyzstan',
  KH: 'cambodia',
  KI: 'kiribati',
  KM: 'comoros',
  KN: 'saint-kitts-and-nevis',
  KP: 'north-korea',
  KR: 'south-korea',
  KW: 'kuwait',
  KZ: 'kazakhstan',
  LA: 'laos',
  LB: 'lebanon',
  LC: 'saint-lucia',
  LI: 'liechtenstein',
  LK: 'sri-lanka',
  LR: 'liberia',
  LS: 'lesotho',
  LT: 'lithuania',
  LU: 'luxembourg',
  LV: 'latvia',
  LY: 'libya',
  MA: 'morocco',
  MC: 'monaco',
  MD: 'moldova',
  ME: 'montenegro',
  MG: 'madagascar',
  MH: 'marshall-islands',
  MK: 'north-macedonia',
  ML: 'mali',
  MM: 'myanmar',
  MN: 'mongolia',
  MO: 'macao',
  MR: 'mauritania',
  MT: 'malta',
  MU: 'mauritius',
  MV: 'maldives',
  MW: 'malawi',
  MX: 'mexico',
  MY: 'malaysia',
  MZ: 'mozambique',
  NA: 'namibia',
  NE: 'niger',
  NG: 'nigeria',
  NI: 'nicaragua',
  NL: 'netherlands',
  NO: 'norway',
  NP: 'nepal',
  NR: 'nauru',
  NZ: 'new-zealand',
  OM: 'oman',
  PA: 'panama',
  PE: 'peru',
  PG: 'papua-new-guinea',
  PH: 'philippines',
  PK: 'pakistan',
  PL: 'poland',
  PS: 'palestine',
  PT: 'portugal',
  PW: 'palau',
  PY: 'paraguay',
  QA: 'qatar',
  RO: 'romania',
  RS: 'serbia',
  RU: 'russia',
  RW: 'rwanda',
  SA: 'saudi-arabia',
  SB: 'solomon-islands',
  SC: 'seychelles',
  SD: 'sudan',
  SE: 'sweden',
  SG: 'singapore',
  SI: 'slovenia',
  SK: 'slovakia',
  SL: 'sierra-leone',
  SM: 'san-marino',
  SN: 'senegal',
  SO: 'somalia',
  SR: 'suriname',
  SS: 'south-sudan',
  ST: 'sao-tome-and-principe',
  SV: 'el-salvador',
  SY: 'syria',
  SZ: 'eswatini',
  TD: 'chad',
  TG: 'togo',
  TH: 'thailand',
  TJ: 'tajikistan',
  TL: 'timor-leste',
  TM: 'turkmenistan',
  TN: 'tunisia',
  TO: 'tonga',
  TR: 'turkiye',
  TT: 'trinidad-and-tobago',
  TV: 'tuvalu',
  TW: 'taiwan',
  TZ: 'tanzania',
  UA: 'ukraine',
  UG: 'uganda',
  US: 'united-states',
  UY: 'uruguay',
  UZ: 'uzbekistan',
  VA: 'vatican-city',
  VC: 'saint-vincent-and-the-grenadines',
  VE: 'venezuela',
  VN: 'vietnam',
  VU: 'vanuatu',
  WS: 'samoa',
  XK: 'kosovo',
  YE: 'yemen',
  ZA: 'south-africa',
  ZM: 'zambia',
  ZW: 'zimbabwe',
};

const codesBySlug = new Map(Object.entries(countrySlugs).map(([code, slug]) => [slug, code]));

export function countrySlug(code: string) {
  return countrySlugs[code.toUpperCase()] ?? code.toLowerCase();
}

/** The country an address segment names. Only its lowercase slug is canonical: a slug in other letter cases, or an
 * ISO code, should redirect to it. */
export function countryFromSegment(segment: unknown): { code: string; canonical: boolean } | undefined {
  if (typeof segment !== 'string') return undefined;
  const code = codesBySlug.get(segment.toLowerCase());
  if (code) return { code, canonical: segment === countrySlugs[code] };
  const upper = segment.toUpperCase();
  return Object.hasOwn(countrySlugs, upper) ? { code: upper, canonical: false } : undefined;
}

/** Every destination's rule for one passport. */
export function passportPath(code: string) {
  return `/passports/${countrySlug(code)}`;
}

/** Every passport's rule for one destination. */
export function destinationPath(code: string) {
  return `/destinations/${countrySlug(code)}`;
}

/** One passport's rule for one destination. */
export function entryPath(destination: string, passport: string) {
  return `${destinationPath(destination)}/${countrySlug(passport)}`;
}
