// The English Wikipedia article that sets out each destination's own visa policy. The Schengen states and Cyprus,
// which applies the same EU visa list, share one. The sync reports titles it cannot find; update this list if Wikipedia
// renames an article.
const schengenArea = 'Visa policy of the Schengen Area';

export const policyPages: Record<string, string> = {
  AD: 'Visa policy of Andorra',
  AE: 'Visa policy of the United Arab Emirates',
  AF: 'Visa policy of Afghanistan',
  AG: 'Visa policy of Antigua and Barbuda',
  AL: 'Visa policy of Albania',
  AM: 'Visa policy of Armenia',
  AO: 'Visa policy of Angola',
  AR: 'Visa policy of Argentina',
  AT: schengenArea,
  AU: 'Visa policy of Australia',
  AZ: 'Visa policy of Azerbaijan',
  BA: 'Visa policy of Bosnia and Herzegovina',
  BB: 'Visa policy of Barbados',
  BD: 'Visa policy of Bangladesh',
  BE: schengenArea,
  BF: 'Visa policy of Burkina Faso',
  BG: schengenArea,
  BH: 'Visa policy of Bahrain',
  BI: 'Visa policy of Burundi',
  BJ: 'Visa policy of Benin',
  BN: 'Visa policy of Brunei',
  BO: 'Visa policy of Bolivia',
  BR: 'Visa policy of Brazil',
  BS: 'Visa policy of the Bahamas',
  BT: 'Visa policy of Bhutan',
  BW: 'Visa policy of Botswana',
  BY: 'Visa policy of Belarus',
  BZ: 'Visa policy of Belize',
  CA: 'Visa policy of Canada',
  CD: 'Visa policy of the Democratic Republic of the Congo',
  CF: 'Visa policy of the Central African Republic',
  CG: 'Visa policy of the Republic of the Congo',
  CH: schengenArea,
  CI: 'Visa policy of Ivory Coast',
  CL: 'Visa policy of Chile',
  CM: 'Visa policy of Cameroon',
  CN: 'Visa policy of mainland China',
  CO: 'Visa policy of Colombia',
  CR: 'Visa policy of Costa Rica',
  CU: 'Visa policy of Cuba',
  CV: 'Visa policy of Cape Verde',
  CY: schengenArea,
  CZ: schengenArea,
  DE: schengenArea,
  DJ: 'Visa policy of Djibouti',
  DK: schengenArea,
  DM: 'Visa policy of Dominica',
  DO: 'Visa policy of the Dominican Republic',
  DZ: 'Visa policy of Algeria',
  EC: 'Visa policy of Ecuador',
  EE: schengenArea,
  EG: 'Visa policy of Egypt',
  ER: 'Visa policy of Eritrea',
  ES: schengenArea,
  ET: 'Visa policy of Ethiopia',
  FI: schengenArea,
  FJ: 'Visa policy of Fiji',
  FM: 'Visa policy of Micronesia',
  FR: schengenArea,
  GA: 'Visa policy of Gabon',
  GB: 'Visa policy of the United Kingdom',
  GD: 'Visa policy of Grenada',
  GE: 'Visa policy of Georgia',
  GH: 'Visa policy of Ghana',
  GM: 'Visa policy of the Gambia',
  GN: 'Visa policy of Guinea',
  GQ: 'Visa policy of Equatorial Guinea',
  GR: schengenArea,
  GT: 'Visa policy of Guatemala',
  GW: 'Visa policy of Guinea-Bissau',
  GY: 'Visa policy of Guyana',
  HK: 'Visa policy of Hong Kong',
  HN: 'Visa policy of Honduras',
  HR: schengenArea,
  HT: 'Visa policy of Haiti',
  HU: schengenArea,
  ID: 'Visa policy of Indonesia',
  IE: 'Visa policy of Ireland',
  IL: 'Visa policy of Israel',
  IN: 'Visa policy of India',
  IQ: 'Visa policy of Iraq',
  IR: 'Visa policy of Iran',
  IS: schengenArea,
  IT: schengenArea,
  JM: 'Visa policy of Jamaica',
  JO: 'Visa policy of Jordan',
  JP: 'Visa policy of Japan',
  KE: 'Visa policy of Kenya',
  KG: 'Visa policy of Kyrgyzstan',
  KH: 'Visa policy of Cambodia',
  KI: 'Visa policy of Kiribati',
  KM: 'Visa policy of the Comoros',
  KN: 'Visa policy of Saint Kitts and Nevis',
  KP: 'Visa policy of North Korea',
  KR: 'Visa policy of South Korea',
  KW: 'Visa policy of Kuwait',
  KZ: 'Visa policy of Kazakhstan',
  LA: 'Visa policy of Laos',
  LB: 'Visa policy of Lebanon',
  LC: 'Visa policy of Saint Lucia',
  LI: schengenArea,
  LK: 'Visa policy of Sri Lanka',
  LR: 'Visa policy of Liberia',
  LS: 'Visa policy of Lesotho',
  LT: schengenArea,
  LU: schengenArea,
  LV: schengenArea,
  LY: 'Visa policy of Libya',
  MA: 'Visa policy of Morocco',
  MC: 'Visa policy of Monaco',
  MD: 'Visa policy of Moldova',
  ME: 'Visa policy of Montenegro',
  MG: 'Visa policy of Madagascar',
  MH: 'Visa policy of the Marshall Islands',
  MK: 'Visa policy of North Macedonia',
  ML: 'Visa policy of Mali',
  MM: 'Visa policy of Myanmar',
  MN: 'Visa policy of Mongolia',
  MO: 'Visa policy of Macau',
  MR: 'Visa policy of Mauritania',
  MT: schengenArea,
  MU: 'Visa policy of Mauritius',
  MV: 'Visa policy of the Maldives',
  MW: 'Visa policy of Malawi',
  MX: 'Visa policy of Mexico',
  MY: 'Visa policy of Malaysia',
  MZ: 'Visa policy of Mozambique',
  NA: 'Visa policy of Namibia',
  NE: 'Visa policy of Niger',
  NG: 'Visa policy of Nigeria',
  NI: 'Visa policy of Nicaragua',
  NL: schengenArea,
  NO: schengenArea,
  NP: 'Visa policy of Nepal',
  NR: 'Visa policy of Nauru',
  NZ: 'Visa policy of New Zealand',
  OM: 'Visa policy of Oman',
  PA: 'Visa policy of Panama',
  PE: 'Visa policy of Peru',
  PG: 'Visa policy of Papua New Guinea',
  PH: 'Visa policy of the Philippines',
  PK: 'Visa policy of Pakistan',
  PL: schengenArea,
  PS: 'Visa policy of Palestine',
  PT: schengenArea,
  PW: 'Visa policy of Palau',
  PY: 'Visa policy of Paraguay',
  QA: 'Visa policy of Qatar',
  RO: schengenArea,
  RS: 'Visa policy of Serbia',
  RU: 'Visa policy of Russia',
  RW: 'Visa policy of Rwanda',
  SA: 'Visa policy of Saudi Arabia',
  SB: 'Visa policy of Solomon Islands',
  SC: 'Visa policy of Seychelles',
  SD: 'Visa policy of Sudan',
  SE: schengenArea,
  SG: 'Visa policy of Singapore',
  SI: schengenArea,
  SK: schengenArea,
  SL: 'Visa policy of Sierra Leone',
  SM: 'Visa policy of San Marino',
  SN: 'Visa policy of Senegal',
  SO: 'Visa policy of Somalia',
  SR: 'Visa policy of Suriname',
  SS: 'Visa policy of South Sudan',
  ST: 'Visa policy of São Tomé and Príncipe',
  SV: 'Visa policy of El Salvador',
  SY: 'Visa policy of Syria',
  SZ: 'Visa policy of Eswatini',
  TD: 'Visa policy of Chad',
  TG: 'Visa policy of Togo',
  TH: 'Visa policy of Thailand',
  TJ: 'Visa policy of Tajikistan',
  TL: 'Visa policy of Timor-Leste',
  TM: 'Visa policy of Turkmenistan',
  TN: 'Visa policy of Tunisia',
  TO: 'Visa policy of Tonga',
  TR: 'Visa policy of Turkey',
  TT: 'Visa policy of Trinidad and Tobago',
  TV: 'Visa policy of Tuvalu',
  TW: 'Visa policy of Taiwan',
  TZ: 'Visa policy of Tanzania',
  UA: 'Visa policy of Ukraine',
  UG: 'Visa policy of Uganda',
  US: 'Visa policy of the United States',
  UY: 'Visa policy of Uruguay',
  UZ: 'Visa policy of Uzbekistan',
  VA: 'Visa policy of Vatican City',
  VC: 'Visa policy of Saint Vincent and the Grenadines',
  VE: 'Visa policy of Venezuela',
  VN: 'Visa policy of Vietnam',
  VU: 'Visa policy of Vanuatu',
  WS: 'Visa policy of Samoa',
  XK: 'Visa policy of Kosovo',
  YE: 'Visa policy of Yemen',
  ZA: 'Visa policy of South Africa',
  ZM: 'Visa policy of Zambia',
  ZW: 'Visa policy of Zimbabwe',
};
