// The English Wikipedia article that lists the entry rules for each passport. The sync script reports titles it
// cannot find; update this list if Wikipedia renames an article.
/** How each article's title names the passport's citizens: "Visa requirements for German citizens". */
export const citizens: Record<string, string> = {
  AD: 'Andorran',
  AE: 'Emirati',
  AF: 'Afghan',
  AG: 'Antigua and Barbuda',
  AL: 'Albanian',
  AM: 'Armenian',
  AO: 'Angolan',
  AR: 'Argentine',
  AT: 'Austrian',
  AU: 'Australian',
  AZ: 'Azerbaijani',
  BA: 'Bosnia and Herzegovina',
  BB: 'Barbadian',
  BD: 'Bangladeshi',
  BE: 'Belgian',
  BF: 'Burkinabe',
  BG: 'Bulgarian',
  BH: 'Bahraini',
  BI: 'Burundian',
  BJ: 'Beninese',
  BN: 'Bruneian',
  BO: 'Bolivian',
  BR: 'Brazilian',
  BS: 'Bahamian',
  BT: 'Bhutanese',
  BW: 'Botswana',
  BY: 'Belarusian',
  BZ: 'Belizean',
  CA: 'Canadian',
  CD: 'Democratic Republic of the Congo',
  CF: 'Central African',
  CG: 'Republic of the Congo',
  CH: 'Swiss',
  CI: 'Ivorian',
  CL: 'Chilean',
  CM: 'Cameroonian',
  CN: 'Chinese',
  CO: 'Colombian',
  CR: 'Costa Rican',
  CU: 'Cuban',
  CV: 'Cape Verdean',
  CY: 'Cypriot',
  CZ: 'Czech',
  DE: 'German',
  DJ: 'Djiboutian',
  DK: 'Danish',
  DM: 'Dominica',
  DO: 'Dominican Republic',
  DZ: 'Algerian',
  EC: 'Ecuadorian',
  EE: 'Estonian',
  EG: 'Egyptian',
  ER: 'Eritrean',
  ES: 'Spanish',
  ET: 'Ethiopian',
  FI: 'Finnish',
  FJ: 'Fijian',
  FM: 'Micronesian',
  FR: 'French',
  GA: 'Gabonese',
  GB: 'British',
  GD: 'Grenadian',
  GE: 'Georgian',
  GH: 'Ghanaian',
  GM: 'Gambian',
  GN: 'Guinean',
  GQ: 'Equatorial Guinean',
  GR: 'Greek',
  GT: 'Guatemalan',
  GW: 'Guinea-Bissauan',
  GY: 'Guyanese',
  HN: 'Honduran',
  HR: 'Croatian',
  HT: 'Haitian',
  HU: 'Hungarian',
  ID: 'Indonesian',
  IE: 'Irish',
  IL: 'Israeli',
  IN: 'Indian',
  IQ: 'Iraqi',
  IR: 'Iranian',
  IS: 'Icelandic',
  IT: 'Italian',
  JM: 'Jamaican',
  JO: 'Jordanian',
  JP: 'Japanese',
  KE: 'Kenyan',
  KG: 'Kyrgyzstani',
  KH: 'Cambodian',
  KI: 'Kiribati',
  KM: 'Comorian',
  KN: 'Saint Kitts and Nevis',
  KP: 'North Korean',
  KR: 'South Korean',
  KW: 'Kuwaiti',
  KZ: 'Kazakhstani',
  LA: 'Laotian',
  LB: 'Lebanese',
  LC: 'Saint Lucian',
  LI: 'Liechtenstein',
  LK: 'Sri Lankan',
  LR: 'Liberian',
  LS: 'Lesotho',
  LT: 'Lithuanian',
  LU: 'Luxembourgish',
  LV: 'Latvian',
  LY: 'Libyan',
  MA: 'Moroccan',
  MC: 'Monégasque',
  MD: 'Moldovan',
  ME: 'Montenegrin',
  MG: 'Malagasy',
  MH: 'Marshall Islands',
  ML: 'Malian',
  MM: 'Myanmar',
  MN: 'Mongolian',
  MR: 'Mauritanian',
  MT: 'Maltese',
  MU: 'Mauritian',
  MV: 'Maldivian',
  MW: 'Malawian',
  MX: 'Mexican',
  MY: 'Malaysian',
  MZ: 'Mozambican',
  NA: 'Namibian',
  NE: 'Nigerien',
  NG: 'Nigerian',
  NI: 'Nicaraguan',
  NL: 'Dutch',
  NO: 'Norwegian',
  NP: 'Nepalese',
  NR: 'Nauruan',
  NZ: 'New Zealand',
  OM: 'Omani',
  PA: 'Panamanian',
  PE: 'Peruvian',
  PG: 'Papua New Guinean',
  PH: 'Philippine',
  PK: 'Pakistani',
  PL: 'Polish',
  PS: 'Palestinian',
  PT: 'Portuguese',
  PW: 'Palauan',
  PY: 'Paraguayan',
  QA: 'Qatari',
  RO: 'Romanian',
  RS: 'Serbian',
  RU: 'Russian',
  RW: 'Rwandan',
  SA: 'Saudi',
  SB: 'Solomon Islands',
  SC: 'Seychellois',
  SD: 'Sudanese',
  SE: 'Swedish',
  SG: 'Singapore',
  SI: 'Slovenian',
  SK: 'Slovak',
  SL: 'Sierra Leonean',
  SM: 'Sammarinese',
  SN: 'Senegalese',
  SO: 'Somali',
  SR: 'Surinamese',
  SS: 'South Sudanese',
  ST: 'Santomean',
  SV: 'Salvadoran',
  SY: 'Syrian',
  SZ: 'Swazi',
  TD: 'Chadian',
  TG: 'Togolese',
  TH: 'Thai',
  TJ: 'Tajikistani',
  TL: 'East Timorese',
  TM: 'Turkmenistani',
  TN: 'Tunisian',
  TO: 'Tongan',
  TR: 'Turkish',
  TT: 'Trinidad and Tobago',
  TV: 'Tuvaluan',
  TW: 'Taiwanese',
  TZ: 'Tanzanian',
  UA: 'Ukrainian',
  UG: 'Ugandan',
  US: 'United States',
  UY: 'Uruguayan',
  UZ: 'Uzbekistan',
  VA: 'Vatican',
  VC: 'Saint Vincent and the Grenadines',
  VE: 'Venezuelan',
  VN: 'Vietnamese',
  VU: 'Vanuatu',
  WS: 'Samoan',
  XK: 'Kosovar',
  YE: 'Yemeni',
  ZA: 'South African',
  ZM: 'Zambian',
  ZW: 'Zimbabwean',
};

export const wikipediaPages: Record<string, string> = {
  ...Object.fromEntries(
    Object.entries(citizens).map(([code, people]) => [code, `Visa requirements for ${people} citizens`])
  ),
  HK: 'Visa requirements for Chinese citizens of Hong Kong',
  MK: 'Visa requirements for citizens of North Macedonia',
  MO: 'Visa requirements for Chinese citizens of Macau',
};
